[tool.ruff]
lint.ignore = ["F841", "E731", "E501"]
lint.extend-select = ["I"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"