User:
  name: OM
  
Save File:
  sample name: TES500
  device type: snspd
  device name: D1
  filepath: S:\SC

iv_sweep:
  start: 0
  stop: !!float 10e-6
  steps: 5
  sweep: 1
  full_sweep: True
  series_resistance: !!float 100e3
  
trigger_sweep:
  start: 0
  stop: 1
  step: .1
  bias_voltage: 0
  attenuation_db: 100
  counting_time: .5
  counter_trigger_voltage: 0

linearity_check:
  bias: !!float 10e-6
  start: 5
  stop: 50
  step: 5
  counting_time: 1
  iterations: 1
  
  
  
photon_counts:
  start: 0
  stop: !!float 10e-6
  step: !!float 2e-6
  trigger_v: 0.5
  counting_time: .5
  iterations: 5
  attenuation_db: 100
    

  
Source:
  name: SIM928
  port: 'GPIB0::2'
  port_alt: 3

Meter:
  name: Keithley2001
  port: 'GPIB0::16'

Scope: 
  name: LeCroy620Zi
  port: '18.62.7.103'
  channel: C2
    
Temperature:
  name: Cryocon350
  port: 'GPIB0::13'
  channel: D4