User:
  name: USER
  
Save File:
  sample name: SPX###
  device type: snspd
  device name: A1
 

iv_sweep:
  start: 0
  stop: !!float 150e-6
  steps: 20
  sweep: 1
  full_sweep: True
  series_resistance: !!float 20e3

pulse_trace:
  bias_voltage: 1.6
  trigger_level: .05
  channel: [C2, C3]
  attenuation: 10

  
trigger_sweep:
  start: 0.
  stop: 0.1
  step: .005
  bias_voltage: 1.6
  attenuation_db: 10
  counting_time: .1



linearity_check:
  bias: !!float 75e-6
  start: 0
  stop: 100
  step: 5
  counting_time: .1
  trigger_v: .04
  iterations: 1


  
photon_counts:
  start: !!float 60e-6
  stop: !!float 89e-6
  step: !!float 1e-6
  trigger_v: .04
  counting_time: .2
  iterations: 5
  attenuation_db: 0
  
  
Laser:
  name: S1FC780
  wavelength_nm: 780
  
Source:
  name: SIM928
  port: 'GPIB0::1'
  port_alt: 3

Meter:
  name: Keithley2700
  port: 'GPIB0::18'

Counter:
  name: Agilent53131a
  port: 'GPIB0::30'

Scope: 
  name: LeCroy620Zi
  port: '18.25.24.38'
  channel: [C2]
    
Attenuator:
  name: JDSHA9
  port: 'GPIB0::7'

Temperature:
  name: ICE
  
# VNA:
#   name: N5224A
#   port: 'GPIB0::16'